- name: check for initalized fixtures
  stat: path={{ fixture_init_file }}
  register: fixture_init

- name: copy fixtures
  copy: src={{ fixture_file }} dest={{ fixture_dest }}
  when: fixture_init.stat.exists == False

- name: install fixtures (mysql)
  shell: bzcat {{ fixture_dest }} | mysql --user={{ database.ddl_username }} --password={{ database.ddl_password }} {{ database.name }}
  when: fixture_init.stat.exists == False and database.type == "mysql"
  register: fixture_init_result

- name: install password file (pgsql)
  template: src=pgpass.j2 dest=/root/.pgpass mode=0600
  when: database.type == "postgres"

- name: install fixtures (pgsql)
  shell: bzcat {{ fixture_dest }} | pg_restore -O -c -Fc -d {{ database.name }}
  when: fixture_init.stat.exists == False and database.type == "postgres"
  sudo_user: postgres
  register: fixture_init_result

- name: mark fixtured initalized
  file: path={{ fixture_init_file }} state=touch
  when: fixture_init_result|success