- name: check for initalized fixtures
  stat: path={{ fixture_init_file }}
  register: fixture_init

- name: copy fixtures
  copy: src={{ fixture_file }} dest={{ fixture_dest }}
  when: fixture_init.stat.exists == False

- name: install fixtures (mysql)
  shell: mysql --user={{ database.ddl_username }} --password={{ database.ddl_password }} {{ database.database }} < {{ fixture_dest }}
  when: fixture_init.stat.exists == False and database.type == "mysql"
  register: fixture_init_result

- name: install fixtures (pgsql)
  shell: psql {{ database.database }} < {{ fixture_dest }}
  sudo_user: postgres
  when: fixture_init.stat.exists == False and database.type == "postgres"
  register: fixture_init_result

- name: mark fixtured initalized
  file: path={{ fixture_init_file }} state=touch
  when: fixture_init_file|success