---
- file: path={{ bigsense_opt }} state=directory owner=root mode=0755

- action: apt update_cache=yes

- include: postgres.yml
  when: database.type == 'postgres'

- include: mysql.yml
  when: database.type == 'mysql'

- include: fixtures.yml
  when: fixture is defined