---
- name: install postgresql
  action: apt name=postgresql

- name: install postgis
  action: apt name=postgresql-9.3-postgis-2.1

- name: enable postgresql
  service: name=postgresql enabled=yes state=started

- name: check if postgresql has been initalized for bigsense
  stat: path={{ dbinit_file }}
  register: dbinit

- name: copy initial DDL template
  template: src=init-pgsql.sql.j2 dest={{ ddl_file }} owner=postgres mode=0400
  when: dbinit.stat.exists == False

- name: initalize postgresql
  sudo_user: postgres
  shell: psql < {{ ddl_file }}
  when: dbinit.stat.exists == False
  register: dbinit_result

- name: mark initilization complete
  file: path={{ dbinit_file }} state=touch
  when: dbinit_result|success

- name: delete DDL template
  file: path={{ ddl_file }} state=absent

- name: add sql connection trust for BigSense server
  lineinfile: dest={{ pg_hba_conf }}
    regexp="^host\s+{{ database.name }}\s+{{ database.username }}\s+.*\s+trust$"
    insertafter="^#\sIPv4\slocal.+"
    line="host {{ database.name }} {{ database.username }},{{ database.ddl_username }} {{ servers.bigsense.ip }}/32 trust"
  notify: 'Restart Postgres'

- name: listen on network adapter
  lineinfile: dest={{ postgresql_conf }}
    regexp="^.*listen_addresses+.*$"
    line="listen_addresses = '{{ servers.database.ip }}'"
  notify: 'Restart Postgres'