#!/usr/bin/env ruby

require_relative 'lib/colours'
require_relative 'lib/create'
require_relative 'lib/destroy'
require_relative 'lib/vagrant'
require_relative 'lib/env'
require_relative 'lib/genkey'
require_relative 'lib/secure'

usage = <<-USAGE
Usage: vsense [ create | list | genkeys | destroy | start | stop | status | secure ]

\t create  - creates a new environment
\t list    - list of all environments
\t genkeys - generate PGP keys for a build environment
\t destroy - stop and delete all files associated with an environment
\t start   - start an environment
\t stop    - stop an environment
\t status  - display the status of an environment
\t secure  - configures production level security for all environments

add -h or --help for additional argumnets for each command
USAGE

subcommands = [ 'create' , 'list' , 'genkeys' , 'destroy' , 'start' , 'stop' , 'status' , 'secure' ]

if !subcommands.include? ARGV[0]
  print usage
  exit 2
end

action = nil
case ARGV[0]
  when 'create'
    action = CreateAction.new(ARGV)
  when 'list'
    Environment::list
    exit 0
  when 'genkeys'
    action = GenKeyAction.new(ARGV)
  when 'destroy'
  	action = DestroyAction.new(ARGV)
  when 'start', 'stop', 'status'
    action = Vagrant.new(ARGV)
  when 'secure'
    action = SecureAction.new(ARGV)
end

action.run

