#!/usr/bin/env python3

import os
import re
from glob import glob

homedir = os.path.expanduser('~')
debs = os.path.join(homedir,'debs')
components = ['nightly', 'testing', 'stable' ]

def repo_name(config_file):
    return os.path.basename(config_file).split('.')[0]

for deb in glob( os.path.join(debs, '*.deb') ):
    for repo_config in glob( os.path.join(homedir, '*.aptly') ):

        version = deb.split('_')[1]
        ends_with_number = re.search(r'\d+$', version)

        if '-' in version:
            component = 'nightly'
        elif ends_with_number is None:
            component = 'testing'
        else:
            component = 'stable'

        cmd = 'aptly -config={} repo add {}-{} {}'.format(
                  repo_config, repo_name(repo_config), component, deb)
        print(cmd)
        os.system(cmd)

    os.unlink(deb)

# Can't get -passphrase-file to work
passphrase = open(os.path.join(homedir,'bigsense.passphrase')).readlines()[0].strip()

for repo_config in glob( os.path.join(homedir, '*.aptly') ):
    cmd = 'aptly -passphrase={} -architectures=all -config={} publish update {}'.format(passphrase, repo_config, repo_name(repo_config))
    print(cmd)
    os.system(cmd)

