#!/usr/bin/env python3

from subprocess import Popen, PIPE
import os
import re
from glob import glob

homedir = os.path.expanduser('~')
debs = os.path.join(homedir,'debs')
components = ['nightly', 'testing', 'stable' ]

def repo_name(config_file):
    return os.path.basename(config_file).split('.')[0]

def run_cmd(cmd):
    print(cmd)
    proc = Popen(cmd,stdout=PIPE)
    for l in iter(proc.stdout.readline, b''):
        print(l.decode('utf-8'),end='')
    proc.communicate()

for deb in glob( os.path.join(debs, '*.deb') ):
    for repo_config in glob( os.path.join(homedir, '*.aptly') ):

        version = deb.split('_')[1]
        ends_with_number = re.search(r'\d+$', version)

        if '-' in version:
            component = 'nightly'
        elif ends_with_number is None:
            component = 'testing'
        else:
            component = 'stable'

        run_cmd(('aptly','-config={}'.format(repo_config),'repo','add','{}-{}'.format(repo_name(repo_config),component),deb))

    os.unlink(deb)

# Can't get -passphrase-file to work
passphrase = open(os.path.join(homedir,'bigsense.passphrase')).readlines()[0].strip()

for repo_config in glob( os.path.join(homedir, '*.aptly') ):
    run_cmd(('aptly', '-passphrase={}'.format(passphrase), '-architectures=all', '-config={}'.format(repo_config), 'publish', 'update', repo_name(repo_config)))
