---
# add aptly repo
- apt_key: keyserver=keys.gnupg.net id=E083A3782A194991
- apt_repository: repo='deb http://repo.aptly.info/ squeeze main' state=present

# Install packages

- action: apt name=dpkg-sig
- action: apt name=aptly

# Create Repo Management User and set permissions

- file: path={{ repoman_home }}/debs/{{ item }} state=directory owner=repoman group=repoman mode=0775
  with_items: repos[0]

# Create aptly repo db

- file: path={{ repoman_home }}/aptly state=directory owner=repoman group=repoman mode=0755
- template: src=aptly.conf.j2 dest={{ aptly_config }} owner=root mode=0644
- command: aptly repo create -comment="bigsense repository" -component={{ item[1] }} -config={{ aptly_config }} {{ item[0] }}-{{ item[1] }} creates={{ repo_init }}
  with_nested: repos
  register: create_repo
  sudo_user: repoman
- file: path={{ repo_init }} state=touch
  when: create_repo|success

# publish repo

- shell: aptly -passphrase=$(cat {{ pgp_passfile }}) -distribution={{ item }} -component={{repos[1]|join(',')}} -config={{ aptly_config }} publish repo {% for i in repos[1] %}{{item}}-{{i}} {% endfor %}  creates={{ publish_init }}
  with_items: repos[0]
  register: publish_repo
  sudo_user: repoman
- file: path={{ publish_init }} state=touch
- file: src={{ repoman_home }}/aptly/public path={{ webroot }}/debs state=link




