---
- user: name=repoman
- action: apt update_cache=yes
- action: apt name=nginx

# Create Web Root

- file: path={{ webroot }} state=directory owner=repoman group=repoman mode=0755

# Copy and Import PGP Keys

- copy: src=../bigsense.pub dest={{ repoman_home }} owner=root group=repoman mode=0650
- copy: src=../bigsense.sec dest={{ repoman_home }} owner=root group=repoman mode=0650
- template: src=bigsense.passphrase.j2 dest={{ pgp_passfile }} owner=repoman mode=0400
- command: gpg --import {{ repoman_home }}/bigsense.sec creates={{ repoman_home }}/.gnupg/secring.gpg
  sudo_user: repoman
- shell: gpg --export -a "{{ pgp.comment }}" > {{ webroot }}/bigsense.io.key
  sudo_user: repoman

# serve repo though nginx
- template: src=nginx.j2 dest=/etc/nginx/sites-available/repo owner=root group=root mode=0644
  notify: 'Reload Nginx'
- file: src=/etc/nginx/sites-available/repo dest=/etc/nginx/sites-enabled/repo owner=root group=root state=link
  notify: 'Reload Nginx'
- file: path=/etc/nginx/sites-enabled/default state=absent
  notify: 'Reload Nginx'
- service: name=nginx enabled=yes state=started

#add publishing script and copy ssh transfer keys

- copy: src=publish dest={{ repoman_home }} owner=root group=repoman mode=0550
- file: path={{ repoman_home }}/.ssh state=directory owner=repoman group=repoman mode=0700
- copy: src=../jenkins.ssh.pub dest={{ repoman_home }}/.ssh/authorized_keys owner=repoman group=repoman mode=0600
# Not sure why this doesn't work
#- authorized_key: user=repoman key={{ lookup('file','/home/sumit/sensespace/vSense/virtual-env/build/jenkins.ssh.pub') }}

# apt (debian) and yum (centos/opensuse) repositories

- include: apt.yml
- include: yum.yml