---

- user: name=confluence

# Install Java

- apt_repository: repo='ppa:webupd8team/java'
- apt: update_cache=yes
- shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
- apt: name=oracle-java8-installer
- apt: name=oracle-java8-set-default

# Setup Database

- apt: name=postgresql
- apt: name=python-psycopg2
- service: name=postgresql enabled=yes state=started
- postgresql_user: name={{ confluence.db_user }} password={{ confluence.db_pass }}
  sudo_user: postgres
- postgresql_db: name={{ confluence.db_name }} owner={{ confluence.db_user }}
  sudo_user: postgres

# Get and extract confluence

- get_url: url={{ package_url }} dest=/opt/{{ package }}
- unarchive: copy=no src=/opt/{{ package }} dest=/opt creates={{ package_base }}
- file: path=/opt/{{ package_base }} owner=root group=root recurse=yes state=directory
- file: src=/opt/{{ package_base }} path={{ confluence_base }} state=link
- file: path={{ confluence_base }}/temp mode=0750 owner=confluence group=confluence
- file: path={{ confluence_base }}/logs mode=0750 owner=confluence group=confluence
- file: path={{ confluence_base }}/work mode=0750 owner=confluence group=confluence

# Configure confluence

- file: path={{ confluence_data }} owner=confluence group=confluence mode=0750 state=directory
- template: src=confluence-init.properties.j2 dest={{ confluence_base }}/confluence/WEB-INF/classes/confluence-init.properties

# BigSense favicon

- copy: src=favicon.ico dest={{ confluence_base }}/confluence/favicon.ico
- copy: src=favicon.ico dest={{ confluence_base }}/confluence/images/icons/favicon.ico
- copy: src=favicon.png dest={{ confluence_base }}/confluence/images/icons/favicon.png

# Upstart

- copy: src=confluence.conf dest=/etc/init/confluence.conf
- service: name=confluence enabled=yes state=started
