---

# Install 1.5 Haproxy package

- apt_repository: repo='ppa:vbernat/haproxy-1.5'
- action: apt update_cache=yes
- action: apt name=haproxy

# Let's Encrypt

- get_url: url={{ certbot_url }} dest={{ certbot_dest }}
- file: path={{ certbot_dest }} mode=0700
- template: src=certbot-cron.j2 dest={{ certbot_cron }} owner=root group=root mode=0700
- cron: name="LetsEncrypt" job="{{ certbot_cron }} > /tmp/letsencrypt.log" day=1 user=root cron_file=letsencrypt

# SSL Keys

- copy: src=../bigsense-ssl.key dest={{ ssl_private }} owner=root group=root mode=0600
- copy: src=../bigsense-ssl.crt dest={{ ssl_private }} owner=root group=root mode=0600
- shell: cat {{ ssl_private }}/bigsense-ssl.crt {{ ssl_private }}/bigsense-ssl.key > {{ bigsense_pem }}
- file: path={{ bigsense_pem }} owner=root group=root mode=0600

# Configuration

- template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg owner=root group=root mode=0644
  notify: 'Reload HAProxy'

# Start

- service: name=haproxy enabled=yes state=started
- shell: "{{ certbot_cron }}"
