---
repos:
  - { version: trusty, distribution: Ubuntu }
  - { version: wheezy, distribution: Debian }
repoman_home: /home/repoman
repo_init: "{{repoman_home}}/.repoinit"
publish_init: "{{repoman_home}}/.published"
timestamp: "{{ ansible_date_time.epoch }}"
startup_delay_s: 30
