---
repos:
  - [ upstart, systemv, systemd ]
  - [ stable, testing, nightly ]
repoman_home: /home/repoman
repo_init: "{{repoman_home}}/.repoinit"
publish_init: "{{repoman_home}}/.published"
timestamp: "{{ ansible_date_time.epoch }}"
pgp_passfile: "{{ repoman_home }}/bigsense.passphrase"
webroot: "{{repoman_home}}/www"
aptly_config: "{{ repoman_home }}/aptly.conf"