- name: update apt cache
  action: apt update_cache=yes

- name: install postgresql
  action: apt name=postgresql
- name: enable postgresql
  service: name=postgresql enabled=yes state=started

- name: install openjdk-7
  action: apt name=openjdk-7-jre

- name: add bigsense repo key
  apt_key: url={{ apt_key }} state=present
- name: add bigsense repo
  apt_repository: repo="{{ apt }}" state=present
- name: install bigsense
  action: apt name=bigsense force=true
- name: configure bigsense
  template: src=templates/application.conf.j2 dest=/etc/bigsense/application.conf owner=root group=bigsense mode=0640

- name: check if postgresql has been initalized for bigsense
  stat: path={{ pginit_file }}
  register: pginit

- name: initalize postgresql
  sudo_user: postgres
  shell: psql < /etc/bigsense/initalize-pgsql.sql
  when: pginit.stat.exists == False
  register: pginit_result

- name: mark initilization complete
  file: path={{ pginit_file }} state=touch
  when: pginit_result|success

- name: enable and start bigsense
  service: name=bigsense enabled=yes state=started
