---
- name: BigSense Build Server
  hosts: build
  sudo: true
  vars_files:
    - ../environment.yml
  roles:
   - ansible-jenkins
   - build
  vars:
    plugins:
      - 'sbt'
      - 'git'
      - 'postbuild-task'
    port: 8080
    prefix: '/build'
    email:
      smtp_host: 'mail.bigsense.io'
      smtp_ssl: 'true'
      default_email_suffix: '@bigsense.io'

