---
- name: LtSense Client
  hosts: ltsense
  sudo: true
  vars_files:
    - ../environment.yml
  roles:
   - { role: security }
   - { role: build-host, when: repository.custom == true }
   - ltsense