---

# Check if password has been generated

- local_action: stat path={{ pgp_password_file }}
  register: local_pgp_password_file
  sudo: False

# Generate password if it doesn't exist

- local_action: command pwgen -s 25 1 #TODO: settings for length
  register: password
  when: local_pgp_password_file.stat.exists == False
  sudo: False

- local_action: file path={{ pgp_password_path }} state=directory
  when: local_pgp_password_file.stat.exists == False
  sudo: False

- local_action: shell echo {{ password.stdout }} | gpg --encrypt --armor -r {{ security.pgp_id }} > {{ pgp_password_file }} creates={{ pgp_password_file }}
  when: local_pgp_password_file.stat.exists == False
  sudo: False

# Decrypt password

- local_action: command gpg --decrypt {{ pgp_password_file }}
  register: password
  sudo: False

# Set it in the VM

- local_action: shell echo {{ password.stdout }} | mkpasswd --method=SHA-512 --stdin
  register: crypt_password
  sudo: False

- user: name=root password={{ crypt_password.stdout }}
- user: name=vagrant password={{ crypt_password.stdout }}