---
bigsense_opt: /opt/bigsense
dbinit_file: "{{ bigsense_opt }}/db-initalized"
fixture_init_file: "{{ bigsense_opt }}/fixtures-initalized"
fixture_file: "{{ fixture }}-data.{{ database.type }}.bz2"
fixture_dest: "{{ bigsense_opt }}/{{ fixture_file }}"
ddl_file: "{{ bigsense_opt }}/init.sql"
pg_etc: /etc/postgresql/9.3/main
pg_hba_conf: "{{ pg_etc }}/pg_hba.conf"
postgresql_conf: "{{ pg_etc }}/postgresql.conf"
my_conf: /etc/mysql/my.cnf