---
name: runtime
type: run
domain: internal
repository:
  custom: false
  protocol: https
  host: repo.bigsense.io
  branch: testing
servers:
  bigsense:
    hostname: bigsense-%env%
    os: ubuntu
    ip: 10.11.1.20
  ltsense:
    hostname: ltsense-%env%
    os: ubuntu
    ip: 10.11.1.21
