---
name: runtime
type: run
domain: internal
repository:
  custom: false
  protocol: https
  host: repo.bigsense.io
  stage: stable
servers:
  bigsense:
    hostname: bigsense-%env%
    os: ubuntu
    ip: 10.11.1.20
  ltsense:
    hostname: ltsense-%env%
    os: ubuntu
    ip: 10.11.1.21
  database:
    hostname: db-%env%
    ip: 10.11.1.22
database:
  type: postgres
  name: bigsense
  username: bigsense
  password: bigsense
  ddl_username: bigsense_ddl
  ddl_password: bigsense_ddl
