---
package: atlassian-confluence-5.6.6.tar.gz
package_url: "http://www.atlassian.com/software/confluence/downloads/binary/{{ package }}"
confluence_data: /opt/confluence-data
confluence_base: /opt/confluence