# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

require './vagrantenv'
vars = VagrantEnv.new('environment.yml')

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.define "haproxy" do |haproxy|
    haproxy.vm.network :private_network, ip: vars.ip('haproxy')
    haproxy.vm.network :public_network, ip: vars.ip_ext('haproxy')
    haproxy.vm.hostname = vars.hostname('haproxy')
    haproxy.hostmanager.aliases = vars.aliases('haproxy')
    haproxy.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/haproxy.yml"
    end
  end

  config.vm.define "wiki" do |wiki|
    wiki.vm.network :private_network, ip: vars.ip('wiki')
    wiki.vm.hostname = vars.hostname('wiki')
    wiki.hostmanager.aliases = vars.aliases('wiki')
    wiki.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
    end
    wiki.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/wiki.yml"
    end
  end



end
